apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    role: vote
    version: v1
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30000
  externalIPs:
    - 192.168.1.51
    - 192.168.1.52
  selector:
    role: vote
    version: v1