version: '3'

services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wp
    volumes:
      - /var/lib/mysql
      - /etc/mysql

  wp:
    depends_on:
      - db
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_PASSWORD: secret
    volumes:
      - /var/www/html
    ports:
      - "8080:80"